server:         true
safe:           true
auto:           true
pygments:       true
markdown:       rdiscount
rdiscount
  extensions:   [smart]

source:         .
exclude: ["config.rb", "sass", ".sass-cache"]
