safe:           true
auto:           true
pygments:       true
markdown:       rdiscount
rdiscount
  extensions:   [smart]

source:         ./
destination:    ./_site
plugins:        ./_plugins

exclude: 
- gallery.sh
- README.textile
- config.rb
- sass
